name: sass_builder_example
description: Example to build .css files from .scss source.
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  build_runner: ^2.7.0
  build_web_compilers: ^4.2.2
  sass_builder:
    path: ../
