name: sass_builder_example
description: Example to build .css files from .scss source.
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.2.0
  sass_builder:
    path: ../
