name: sass_builder
version: 0.2.0+1
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/sass_builder
description: Transpile sass files using the "build" package.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  sass: ^1.0.0-beta.2
  build: ^0.10.1
  build_runner: ^0.4.0
  logging: ^0.11.3
  package_resolver: ^1.0.2
  path: ^1.4.1
  scratch_space: ^0.0.1
dev_dependencies:
  bootstrap_sass: 4.0.0-alpha.5+1
  build_test: ^0.8.0
  test: ^0.12.0
#  bootstrap_sass:
#    path: ../bootstrap_sass
