name: sass_builder
version: 2.3.1
repository: https://github.com/dart-league/sass_builder
description: Transpile sass files using the "build" package.

environment:
  sdk: ^3.6.0

dependencies:
  build: '>=3.0.0 <5.0.0'
  build_config: ^1.2.0
  path: ^1.8.0
  sass: ^1.74.0

dev_dependencies:
  build_test: ^3.3.2
  lints: ^6.0.0
  test: ^1.24.0
  source_maps: ^0.10.13
